// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYT8HVJbCIDKCY6bOVmHNitrvEwisuOuI',
    appId: '1:968245394731:web:674fe1891176f4ae68d96e',
    messagingSenderId: '968245394731',
    projectId: 'r-first-flutter-firebase',
    authDomain: 'r-first-flutter-firebase.firebaseapp.com',
    storageBucket: 'r-first-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoykuejhfc-MngNQJlzh1TnBPKCwVB93E',
    appId: '1:968245394731:android:0d9c9b7434082b5568d96e',
    messagingSenderId: '968245394731',
    projectId: 'r-first-flutter-firebase',
    storageBucket: 'r-first-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVqnAJasbKSMrSd7mZY1utvBo2tQsTjiE',
    appId: '1:968245394731:ios:c35042bf0998166a68d96e',
    messagingSenderId: '968245394731',
    projectId: 'r-first-flutter-firebase',
    storageBucket: 'r-first-flutter-firebase.appspot.com',
    iosClientId: '968245394731-3ad42hd7mv7mknduj7m6j2mgh4516pj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodHooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVqnAJasbKSMrSd7mZY1utvBo2tQsTjiE',
    appId: '1:968245394731:ios:c35042bf0998166a68d96e',
    messagingSenderId: '968245394731',
    projectId: 'r-first-flutter-firebase',
    storageBucket: 'r-first-flutter-firebase.appspot.com',
    iosClientId: '968245394731-3ad42hd7mv7mknduj7m6j2mgh4516pj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodHooks',
  );
}
